### ISSUE TITLE
ansible.builtin.apt -> name accepts a list, no loop needed

### ISSUE THREAD

**Issue by ryanreece** [garrettskj/dotfiles#1]
https://github.com/garrettskj/dotfiles/blob/5aee0a7c3ffd5f9360b42a39affecff40dc085b9/roles/workstation/tasks/main.yml#L21

btw, you can just use a list of package names instead of looping:

```
- name: PB01T001 - Install System Packages - Ubuntu/Debian/POPOS
  become: yes
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - wget
      - zram-config
      - htop
      - xz-utils
      - net-tools
      - tmux
      - minicom
      - openssh-server
      - whois
      - vlan
      - inxi
      - apt-transport-https
      - gpg
      - ca-certificates
    update_cache: yes
    state: present
```

Ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-name
